-- apply changes
create schema if not exists collezioni;

create table beyblade (
  id                            integer generated by default as identity not null,
  descriptionItem               TEXT,
  owned                         boolean default false not null,
  wish                          boolean default false not null,
  quantityItem                  integer,
  name_category                 integer,
  note                          TEXT,
  nameItem                      varchar(255),
  formato                       varchar(11),
  constraint ck_beyblade_formato check ( formato in ('TAKARA_TOMY','HASBRO')),
  constraint uq_beyblade_nameitem unique (nameItem),
  constraint pk_beyblade primary key (id)
);

create table beyblade_tipo_beyblade_ratchet (
  beyblade_id                   integer not null,
  tipo_beyblade_ratchet_id      integer not null,
  constraint pk_beyblade_tipo_beyblade_ratchet primary key (beyblade_id,tipo_beyblade_ratchet_id)
);

create table beyblade_tipo_beyblade_punte (
  beyblade_id                   integer not null,
  tipo_beyblade_punte_id        integer not null,
  constraint pk_beyblade_tipo_beyblade_punte primary key (beyblade_id,tipo_beyblade_punte_id)
);

create table beyblade_tipo_beyblade_blades (
  beyblade_id                   integer not null,
  tipo_beyblade_blades_id       integer not null,
  constraint pk_beyblade_tipo_beyblade_blades primary key (beyblade_id,tipo_beyblade_blades_id)
);

create table cards (
  id                            integer generated by default as identity not null,
  name_category                 integer,
  constraint pk_cards primary key (id)
);

create table collezioni.category (
  id                            integer generated by default as identity not null,
  name_category                 varchar(255) not null,
  constraint pk_category primary key (id)
);

create table pokemon (
  id                            integer generated by default as identity not null,
  descriptionItem               TEXT,
  owned                         boolean default false not null,
  wish                          boolean default false not null,
  quantityItem                  integer,
  BuyPrice                      float,
  CurrentPrice                  float,
  cards_id                      integer,
  nameItem                      varchar(255),
  languageItem                  varchar(255),
  set_carte                     varchar(255),
  cardNumber                    varchar(255),
  constraint uq_pokemon_nameitem unique (nameItem),
  constraint pk_pokemon primary key (id)
);

create table test_table (
  id                            bigint generated by default as identity not null,
  name                          varchar(255) not null,
  description                   varchar(255),
  constraint pk_test_table primary key (id)
);

create table tipo_beyblade_blades (
  id                            integer generated by default as identity not null,
  weight                        float,
  owned                         boolean default false not null,
  spin                          varchar(5) not null,
  type                          varchar(7),
  nameBlades                    varchar(255) not null,
  constraint ck_tipo_beyblade_blades_spin check ( spin in ('RIGHT','LEFT')),
  constraint ck_tipo_beyblade_blades_type check ( type in ('ATTACK','DEFENSE','STAMINA','BALANCE')),
  constraint pk_tipo_beyblade_blades primary key (id)
);

create table tipo_beyblade_blades_beyblade (
  tipo_beyblade_blades_id       integer not null,
  beyblade_id                   integer not null,
  constraint pk_tipo_beyblade_blades_beyblade primary key (tipo_beyblade_blades_id,beyblade_id)
);

create table tipo_beyblade_punte (
  id                            integer generated by default as identity not null,
  weight                        float not null,
  originBeyFrom                 TEXT,
  owned                         boolean default false not null,
  namePoint                     varchar(255) not null,
  constraint pk_tipo_beyblade_punte primary key (id)
);

create table tipo_beyblade_punte_beyblade (
  tipo_beyblade_punte_id        integer not null,
  beyblade_id                   integer not null,
  constraint pk_tipo_beyblade_punte_beyblade primary key (tipo_beyblade_punte_id,beyblade_id)
);

create table tipo_beyblade_ratchet (
  id                            integer generated by default as identity not null,
  Bumps                         integer not null,
  Height                        integer not null,
  Weight                        float not null,
  originBeyFrom                 TEXT,
  owned                         boolean not null,
  name_ratchet                  varchar(255) not null,
  constraint pk_tipo_beyblade_ratchet primary key (id)
);

create table tipo_beyblade_ratchet_beyblade (
  tipo_beyblade_ratchet_id      integer not null,
  beyblade_id                   integer not null,
  constraint pk_tipo_beyblade_ratchet_beyblade primary key (tipo_beyblade_ratchet_id,beyblade_id)
);

create table tipo_cards_rarity (
  pokemon_id                    integer,
  cards_rarity                  varchar(255) not null,
  constraint pk_tipo_cards_rarity primary key (cards_rarity)
);

-- foreign keys and indices
create index ix_beyblade_name_category on beyblade (name_category);
alter table beyblade add constraint fk_beyblade_name_category foreign key (name_category) references collezioni.category (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_ratchet_beyblade on beyblade_tipo_beyblade_ratchet (beyblade_id);
alter table beyblade_tipo_beyblade_ratchet add constraint fk_beyblade_tipo_beyblade_ratchet_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_ratchet_tipo_beyblade_ratchet on beyblade_tipo_beyblade_ratchet (tipo_beyblade_ratchet_id);
alter table beyblade_tipo_beyblade_ratchet add constraint fk_beyblade_tipo_beyblade_ratchet_tipo_beyblade_ratchet foreign key (tipo_beyblade_ratchet_id) references tipo_beyblade_ratchet (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_punte_beyblade on beyblade_tipo_beyblade_punte (beyblade_id);
alter table beyblade_tipo_beyblade_punte add constraint fk_beyblade_tipo_beyblade_punte_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_punte_tipo_beyblade_punte on beyblade_tipo_beyblade_punte (tipo_beyblade_punte_id);
alter table beyblade_tipo_beyblade_punte add constraint fk_beyblade_tipo_beyblade_punte_tipo_beyblade_punte foreign key (tipo_beyblade_punte_id) references tipo_beyblade_punte (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_blades_beyblade on beyblade_tipo_beyblade_blades (beyblade_id);
alter table beyblade_tipo_beyblade_blades add constraint fk_beyblade_tipo_beyblade_blades_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_beyblade_tipo_beyblade_blades_tipo_beyblade_blades on beyblade_tipo_beyblade_blades (tipo_beyblade_blades_id);
alter table beyblade_tipo_beyblade_blades add constraint fk_beyblade_tipo_beyblade_blades_tipo_beyblade_blades foreign key (tipo_beyblade_blades_id) references tipo_beyblade_blades (id) on delete restrict on update restrict;

create index ix_cards_name_category on cards (name_category);
alter table cards add constraint fk_cards_name_category foreign key (name_category) references collezioni.category (id) on delete restrict on update restrict;

create index ix_pokemon_cards_id on pokemon (cards_id);
alter table pokemon add constraint fk_pokemon_cards_id foreign key (cards_id) references cards (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_blades_beyblade_tipo_beyblade_blades on tipo_beyblade_blades_beyblade (tipo_beyblade_blades_id);
alter table tipo_beyblade_blades_beyblade add constraint fk_tipo_beyblade_blades_beyblade_tipo_beyblade_blades foreign key (tipo_beyblade_blades_id) references tipo_beyblade_blades (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_blades_beyblade_beyblade on tipo_beyblade_blades_beyblade (beyblade_id);
alter table tipo_beyblade_blades_beyblade add constraint fk_tipo_beyblade_blades_beyblade_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_punte_beyblade_tipo_beyblade_punte on tipo_beyblade_punte_beyblade (tipo_beyblade_punte_id);
alter table tipo_beyblade_punte_beyblade add constraint fk_tipo_beyblade_punte_beyblade_tipo_beyblade_punte foreign key (tipo_beyblade_punte_id) references tipo_beyblade_punte (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_punte_beyblade_beyblade on tipo_beyblade_punte_beyblade (beyblade_id);
alter table tipo_beyblade_punte_beyblade add constraint fk_tipo_beyblade_punte_beyblade_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_ratchet_beyblade_tipo_beyblade_ratchet on tipo_beyblade_ratchet_beyblade (tipo_beyblade_ratchet_id);
alter table tipo_beyblade_ratchet_beyblade add constraint fk_tipo_beyblade_ratchet_beyblade_tipo_beyblade_ratchet foreign key (tipo_beyblade_ratchet_id) references tipo_beyblade_ratchet (id) on delete restrict on update restrict;

create index ix_tipo_beyblade_ratchet_beyblade_beyblade on tipo_beyblade_ratchet_beyblade (beyblade_id);
alter table tipo_beyblade_ratchet_beyblade add constraint fk_tipo_beyblade_ratchet_beyblade_beyblade foreign key (beyblade_id) references beyblade (id) on delete restrict on update restrict;

create index ix_tipo_cards_rarity_pokemon_id on tipo_cards_rarity (pokemon_id);
alter table tipo_cards_rarity add constraint fk_tipo_cards_rarity_pokemon_id foreign key (pokemon_id) references pokemon (id) on delete restrict on update restrict;

