version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: collection_db
    environment:
      POSTGRES_DB: collezioni
      POSTGRES_USER: collezioni_owner
      POSTGRES_PASSWORD: '1234'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

