version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: collection_db
    environment:
      POSTGRES_DB: collezioni
      POSTGRES_USER: collezioni_owner
      POSTGRES_PASSWORD: '1234'
#      PGDATA: /data/postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
